(function() {
  var NAV_HTML = "<nav id=\"nav\">\n  <a href=\"#\" class=\"nav-logo\">\n    <svg class=\"nav-logo-mark\" viewBox=\"0 0 40 40\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"20\" cy=\"20\" r=\"18\" fill=\"none\" stroke=\"#B8924A\" stroke-width=\"1\"/>\n      <circle cx=\"20\" cy=\"20\" r=\"12\" fill=\"none\" stroke=\"#B8924A\" stroke-width=\"0.7\" opacity=\"0.6\"/>\n      <path d=\"M20 4 L20 36 M4 20 L36 20\" stroke=\"#B8924A\" stroke-width=\"0.5\" opacity=\"0.4\"/>\n      <circle cx=\"20\" cy=\"20\" r=\"4\" fill=\"#B8924A\"/>\n    </svg>\n    <span class=\"nav-logo-text\">Vedic Trails</span>\n  </a>\n  <ul class=\"nav-links\">\n    <li><a href=\"journeys.html\"><span style=\"display:flex;flex-direction:column;align-items:center;line-height:1.1\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65\">यात्रा</span><span>Yatras</span></span></a></li>\n        <li><a href=\"signature-journeys.html\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65;font-weight:400\">विशिष्ट</span><span>Signature</span></a></li>\n    <li><a href=\"vedic-trails-homepage-v20.html#sacred-geography\"><span style=\"display:flex;flex-direction:column;align-items:center;line-height:1.15;gap:1px\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65;font-weight:400\">पवित्र भूगोल</span><span>Sacred Geography</span></span></a></li>\n    \n    <li><a href=\"calendar.html\"><span style=\"display:flex;flex-direction:column;align-items:center;line-height:1.15;gap:1px\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65;font-weight:400\">पंचांग</span><span>Calendar</span></span></a></li>\n    <li><a href=\"stories.html\"><span style=\"display:flex;flex-direction:column;align-items:center;line-height:1.15;gap:1px\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65;font-weight:400\">कथाएँ</span><span>Stories</span></span></a></li>\n  </ul>\n  <a href=\"quiz.html\" class=\"nav-cta\"><span style=\"display:flex;flex-direction:column;align-items:center;line-height:1.15;gap:1px\"><span style=\"font-family:'Noto Serif Devanagari',serif;font-size:0.72rem;opacity:0.65;font-weight:400\">यात्रा खोज</span><span>Find My Yatra</span></span></a>\n  <button class=\"mobile-menu-btn\" aria-label=\"Menu\">☰</button>\n</nav>";
  document.addEventListener('DOMContentLoaded', function() {
    var existing = document.querySelector('nav');
    if (existing) {
      var tmp = document.createElement('div');
      tmp.innerHTML = NAV_HTML;
      var newNav = tmp.firstElementChild;
      existing.parentNode.replaceChild(newNav, existing);
    }
  });
})();